
package ru.itmo.soa.client.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DemoImpl", targetNamespace = "http://ws.server.soa.itmo.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DemoImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hi", targetNamespace = "http://ws.server.soa.itmo.ru/", className = "ru.itmo.soa.server.ws.Hi")
    @ResponseWrapper(localName = "hiResponse", targetNamespace = "http://ws.server.soa.itmo.ru/", className = "ru.itmo.soa.server.ws.HiResponse")
    @Action(input = "http://ws.server.soa.itmo.ru/DemoImpl/hiRequest", output = "http://ws.server.soa.itmo.ru/DemoImpl/hiResponse")
    public String hi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloWorld", targetNamespace = "http://ws.server.soa.itmo.ru/", className = "ru.itmo.soa.server.ws.HelloWorld")
    @ResponseWrapper(localName = "helloWorldResponse", targetNamespace = "http://ws.server.soa.itmo.ru/", className = "ru.itmo.soa.server.ws.HelloWorldResponse")
    @Action(input = "http://ws.server.soa.itmo.ru/DemoImpl/helloWorldRequest", output = "http://ws.server.soa.itmo.ru/DemoImpl/helloWorldResponse")
    public String helloWorld();

}
